name: "기능 추가"
description: "새로운 기능을 제안합니다"
title: "[기능] "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        ## Not Now 프로젝트 기능 요청
        망설임을 기록하는 쇼핑 경험을 위한 기능을 제안해주세요.

  - type: dropdown
    id: category
    attributes:
      label: "카테고리"
      description: "어떤 영역의 기능인가요?"
      options:
        - "홈 화면"
        - "지금 상태 (상태 선택)"
        - "보관함"
        - "기록 (히스토리)"
        - "내 정보"
        - "상품 상세"
        - "공통 컴포넌트"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "설명"
      description: "어떤 기능인지 설명해주세요"
      placeholder: "ex) 사용자가 상태를 선택할 수 있는 UI를 구현합니다"
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: "작업 내용"
      description: "구체적인 작업 목록을 작성해주세요"
      value: |
        - [ ]
        - [ ]
        - [ ]
    validations:
      required: true

  - type: textarea
    id: reference
    attributes:
      label: "참고 자료"
      description: "디자인, API 문서 등 참고 자료가 있다면 첨부해주세요"
      placeholder: "피그마 링크, 스크린샷 등"
    validations:
      required: false
